### PR TITLE
Improving examples

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Review by jhlegarreta — APPROVED** [review]
Thanks for doing this @dzenanz !

It's been a while since I last built and edited the files in this remote, but :100: for any change that fixes and improves them !

**Review by thewtex — APPROVED** [review]
Any ideas why the macOS builds are failing?

**Comment by dzenanz** [comment]
I am looking into it.

**Comment by dzenanz** [comment]
I tried building and running on Mac, and there were no problems. I did a trivial amend to re-trigger the CI.

**Comment by dzenanz** [comment]
This time around, CI came back green.

**Pull request merged**
