### PR TITLE
 ENH: Providing ITKv5 updates for C++11.

### PR DESCRIPTION
**Pull request by jhlegarreta**
This pull request incorporates code changes that happened in parallel with updating the core ITK code to ITKv5.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Thanks to the awesome scripts Hans and Niels contributed with, this has been a lot easier and fun.

The code yields the same errors (MSVC 2015) as the upstream version, so #6 hopefully fixes them.

A couple of things are still missing:
- I was not able to properly run the `replaceClassWithTypename.py` script; it made some funky sort of changes.
- The script to use the `auto` keyword required clang. Could any of you please run it and add that commit to this PR?
- In the case of the change of `typedef` to `using` I did not find the appropriate script. Anybody?

Thanks.
JON HAITZ

**Review by dzenanz — APPROVED** [review]
Great!

**Review by Besler — APPROVED** [review]
Looks great to me!

**Comment by jhlegarreta** [comment]
Still missing to add these:

>  I was not able to properly run the replaceClassWithTypename.py script; it made some funky sort of changes.
>  The script to use the auto keyword required clang. Could any of you please run it and add that commit to this PR?
>  In the case of the change of typedef to using I did not find the appropriate script. Anybody?

As said, I gave the first a try, but did not do things nicely.

**Comment by dzenanz** [comment]
Well, this can be merged so @Besler can synchronize the repos. The completion of the work can be done later.

**Comment by thewtex** [comment]
> * In the case of the change of `typedef` to `using` I did not find the appropriate script. Anybody?

@hjmjohnson noted changes in the commit message here:

https://github.com/InsightSoftwareConsortium/ITK/commit/66e5d6b3bcc28f1a85b702086b6cedc8cab6723b

These could be added to an inline `sed` script embedded in a bash script to be reproducibly invoked.

**Review by thewtex — APPROVED** [review]
Very nice @jhlegarreta

**Pull request merged**
