### PR TITLE
ENH: big merge

### PR DESCRIPTION
**Pull request by dzenanz**
This is a merge of two development branches with conflict resolution. Requesting feedback. A mirror of https://github.com/Besler/ITKBoneEnhancement/pull/19 for additional CI testing.

### CODE REVIEW

**Comment by dzenanz** [comment]
Wrapping fix in https://github.com/InsightSoftwareConsortium/ITK/pull/1429.

**Review by jhlegarreta — COMMENTED** [review]
Thanks for doing this @dzenanz !

A few comments:
- It looks like the PR in Bryce's repository is different from this one: 45 vs. 66 commits.
- A while ago I opened a [few issues](https://github.com/Besler/ITKBoneEnhancement/issues) in Bryce's repository. Some may have been solved/addressed by these commits (e.g. an appropriate/minimal description seems to have been added to the module). You may want to mark the relevant issues as fixed in the PR message in Bryce's repository.
- It's been a while since I last looked at the repository. I was not aware that @Besler continued to work on it (there are a few commits from Oct 19, 2018). I am fine with any change that improves it. And I believe this series of commits do so.

I'd be grateful if an explanation to the difference in the number of commits of the PRs could be provided (may be it's just merge commits) since the PR says that this is a mirror of the upstream PR.

I'd be happy to approve.

**Comment by dzenanz** [comment]
Bryce's repo has a different starting point from this repo, hence different number of new commits. The content is identical - I am pulling the exact same branch from my fork.
> I was not aware that @Besler continued to work on it

Me neither.

Before we merge this, we need to update ModuleCI to point at or past the merge commit of https://github.com/InsightSoftwareConsortium/ITK/pull/1429.

**Comment by dzenanz** [comment]
@thewtex https://github.com/InsightSoftwareConsortium/ITK/pull/1429 was merged and I pushed the docker image to tag [latest](https://hub.docker.com/repository/docker/insighttoolkit/module-ci/tags?page=1) but the build failure persists. What did I miss?

**Comment by dzenanz** [comment]
For the record: I missed [test/azure-pipelines.yml](https://github.com/InsightSoftwareConsortium/ITKBoneEnhancement/blob/c7843f78d1f33b030b48a855589414ba416ce6c6/test/azure-pipelines.yml#L3)'s specification of versions. Resolving this will take a new Python package release.

**Comment by jhlegarreta** [comment]
> Bryce's repo has a different starting point from this repo, hence different number of new commits. The content is identical - I am pulling the exact same branch from my fork.
> 
> > I was not aware that @Besler continued to work on it
> 
> Me neither.
> 
> Before we merge this, we need to update ModuleCI to point at or past the merge commit of [InsightSoftwareConsortium/ITK#1429](https://github.com/InsightSoftwareConsortium/ITK/pull/1429).

OK. Thanks for the explanation @dzenanz .

**Comment by dzenanz** [comment]
I think this is now ready to merge. Issues to be closed are marked in https://github.com/Besler/ITKBoneEnhancement/pull/19.

**Comment by jhlegarreta** [comment]
Thanks @dzenanz ! Looks good to me then !

**Review by jhlegarreta — APPROVED** [review]

**Pull request merged**
