### PR TITLE
Sync with upstream fork.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Bring upstream fork changes to current master.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex looks like CI builds were not triggered ☹️

**Comment by thewtex** [comment]
@jhlegarreta enabled now :+1:

**Comment by jhlegarreta** [comment]
Thanks @thewtex 🎆. So we merge this hoping that it'll be OK since @Besler 's is green, and check again for the rest of active PR's?

**Comment by jhlegarreta** [comment]
Closing in favor of #4 (cleaner; bring directly from upstream instead of from my own fork).

**Pull request closed without merging**
